services:
  - type: web
    name: whanau-tech
    runtime: python
    build:
      workingDir: .
    buildCommand: |
      pip install -r requirements.txt
      cd ../my_app && npm install && npm run build
      mv ../my_app/build ./build
    startCommand: gunicorn backend.wsgi:app
    envVars:
      - key: SECRET_KEY
        value: R8f3$7kd!LpZ0q2@5mXb9TzY1wQe
      - key: JWT_SECRET_KEY
        value: aB3#kLp0!xY2qVz9RmX7Tzw5@Sd
      - key: MAIL_USERNAME
        value: divyalamichhane@gmail.com
      - key: MAIL_PASSWORD
        value: X9v#rT7p!Lm3$Qs8Zj2@WfB0
      - key: REACT_APP_BACKEND_URL
        value: https://whanau-tech.onrender.com

    buildFilter:
      paths:
        - backend/**
        - my_app/**
