services:
  - type: web
    name: whanau-tech
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd my_app && npm install && npm run build
      mv my_app/build backend/
    startCommand: gunicorn backend.app:app
    envVars:
      - key: SECRET_KEY
        value: your_flask_secret_key
      - key: JWT_SECRET_KEY
        value: your_jwt_secret
      - key: MAIL_USERNAME
        value: your_email@example.com
      - key: MAIL_PASSWORD
        value: your_email_password
